#!/usr/bin/env ruby

# Simulate rubygems adding the top level appliance_console.rb's directory to the path.
$LOAD_PATH.push("#{File.dirname(__FILE__)}/../lib")

require 'pp'
require 'authconfig'
require 'sssd_conf'

module MiQLdapToSssd
  LOGGER = Logger.new('miq_ldap_to_sssd.log')

  LOGGER.formatter = proc do |severity, time, progname, msg|
    "[#{time}] #{severity}: #{msg}\n"
  end

  if __FILE__ == $PROGRAM_NAME
    LOGGER.debug("Running #{$PROGRAM_NAME}")

    initial_settings = MiqLdapConfiguration.initial_settings
    LOGGER.debug("Initial Settings #{initial_settings}")
    pp initial_settings # JJV Remove
    MiqLdapAuthConfig.new(initial_settings).run_auth_config
    SssdConf.new(initial_settings).update
    MiqLdapApacheConfig.new(initial_settings).configure
    MiqLdapSELinuxConfig.new(initial_settings).configure
  end
end
