#!/usr/bin/env ruby

# Simulate rubygems adding the top level appliance_console.rb's directory to the path.
$LOAD_PATH.push("#{File.dirname(__FILE__)}/../lib")

require 'pp'
require 'sssd_conf'

module MiQLdapToSssd
  if __FILE__ == $PROGRAM_NAME
    SssdConf.new.update
  end
end
