#!/usr/bin/env ruby

# Simulate rubygems adding the top level appliance_console.rb's directory to the path.
$LOAD_PATH.push("#{File.dirname(__FILE__)}/../lib/miq_ldap_sssd")

require 'pp'

require 'sssd_conf'
require 'sssd_conf/domain'
require 'sssd_conf/sssd'
require 'sssd_conf/pam'
require 'sssd_conf/ifp'


module MiQLdapToSssd
  if __FILE__ == $PROGRAM_NAME
    SssdConf.new.update
  end
end
